[package]
name = "stop-on-call"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.1" }
hyper = { version = "1.5.2", features = ["server"] }
tokio = { version = "1.43.0", features = ["full"] }
tokio-util = "0.7.13"
